---
- include_tasks: unpack.yml

- name: git clone
  git:
   repo: "{{ git_url }}"
   dest: "{{ playbook_dir }}/{{ git_clone_path }}"
   accept_hostkey: yes
   key_file: "{{ git_temp_file.path }}"

- name: git switch branch
  shell: git checkout "{{ git_branch }}"
  args:
    chdir: "{{ playbook_dir }}/{{ git_clone_path }}"
